name: "Lint"
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      lint: ${{ steps.filter.outputs.lint }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            lint:
              - '*.md'
              - '.editorconfig'
              - '.github/workflows/lint.yml'

  lint:
    name: Lint files
    needs: changes
    if: ${{ needs.changes.outputs.lint == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install prettier
        run: npm install -g prettier

      - name: Check markdown formatting
        run: prettier --check '**.md' '**.yml'
