name: "Lint"
on:
  push:
    branches: ["main"]
    paths: &lint_paths
      - "*.md"
      - ".editorconfig"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: ["main"]
    paths:
      - *lint_paths

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install prettier
        run: npm install -g prettier

      - name: Check markdown formatting
        run: prettier --check "*.md"
